//! Activity classification on the convex arm, and the rule it is easiest to
//! misread.
//!
//! # Why this file exists
//!
//! The convex arm had one boolean weak-activity screen against a fixed relative
//! threshold and two flat index lists — no `AMBIGUOUS`, no μ-scaling, no
//! statuses. It now runs `pounce_sens_core::activity_kernel`, the same decision
//! the NLP arm makes, so the two arms cannot drift on what a kink is. This file
//! guards the *derivation* that feeds it, which is the half that genuinely
//! differs between arms and so the half nothing else checks.
//!
//! # The rule this file exists to state as a test
//!
//! `AMBIGUOUS` is **not** "probably not a kink". The cheap curvature a
//! classifier has to hand is the Hessian diagonal (for a variable) or the
//! curvature along the row's own gradient (for a row). The multiplier is
//! generated by the curvature *reduced* along that coordinate — what is left
//! after the other free coordinates re-optimize. So the ratio is
//! `reduced/diagonal`, which equals 1 only when the coordinate is **decoupled**,
//! and a genuine kink on a coupled coordinate lands in `AMBIGUOUS` at any
//! tolerance.
//!
//! That inference — ambiguous, therefore no kink — is what shipped gh#763 on the
//! NLP arm. `an_ambiguous_verdict_does_not_mean_no_kink` builds the same trap
//! here and asserts the classifier falls into it, so the limitation is a pinned
//! property rather than a footnote someone can skip.
//!
//! Note what that test does **not** claim: that the classifier is wrong. It is
//! answering the question it was asked, cheaply and correctly. The error would
//! be a caller reading the answer as a different question's.
//!
//! # What this file is NOT evidence about
//!
//! - **A reduced-curvature refinement.** The NLP arm answers the coupled case
//!   with `reduced_activity` / `reduced_row_activity`, one back-solve per index.
//!   The convex arm has no such accessor yet; this file pins the gap rather than
//!   closing it.
//! - **Scale invariance.** Every fixture here is unit-scaled. The convex arm
//!   still has no scale-invariance leg.
//! - **Agreement with the NLP arm's numbers.** Both call the same kernel, but
//!   `μ` here is the *achieved* complementarity rather than the barrier
//!   parameter the last iteration ran at, so the two agree on bands, not on bits
//!   — see `the_mu_is_the_achieved_complementarity`.
//!
//! # Mutation evidence
//!
//! Each row was **run**, compile-checked, with `--no-fail-fast`:
//!
//! | mutation | red here |
//! |---|---|
//! | a variable's `Σ` drops the upper-bound term (`z_ub/s_ub`) | `an_upper_bound_is_classified_from_its_own_side`, `a_held_bound_a_slack_bound_and_a_free_variable_are_told_apart` |
//! | a row's `q` and `Σ` skip the `‖∇g‖²` weighting | `a_row_classification_is_unmoved_by_rescaling_the_row` |
//! | the curvature floor is `0.0` | `a_flat_direction_is_unidentified_not_inactive` |
//!
//! The second row is not hypothetical: the first draft of this module divided
//! `Σ` by `‖∇g‖⁴` and left `q` un-normalized, which leaves the verdict scaling
//! as `c⁻⁸` under a row rescale. `a_row_classification_is_unmoved_by_rescaling_
//! the_row` caught it before the code was committed, which is the only reason
//! it is a footnote rather than an entry in this repository's defect history.

use pounce_convex::QpOptions;
use pounce_convex::ipm::solve_qp_ipm;
use pounce_convex::qp::{QpProblem, QpStatus, Triplet};
use pounce_convex::sensitivity::QpSensitivity;
use pounce_feral::FeralSolverInterface;
use pounce_linsol::SparseSymLinearSolverInterface;
use pounce_sens_core::activity_kernel::{
    AMBIGUOUS, INACTIVE, STRONGLY_ACTIVE, UNBOUNDED, UNIDENTIFIED, WEAKLY_ACTIVE,
};

fn backend() -> Box<dyn SparseSymLinearSolverInterface> {
    Box::new(FeralSolverInterface::new())
}

fn tri(row: usize, col: usize, val: f64) -> Triplet {
    Triplet { row, col, val }
}

fn solved(prob: &QpProblem) -> QpSensitivity {
    let opts = QpOptions::default();
    let sol = solve_qp_ipm(prob, &opts, backend);
    assert_eq!(sol.status, QpStatus::Optimal, "fixture must solve");
    match QpSensitivity::build(prob, &sol, &opts, 1e-7, backend) {
        Ok(s) => s,
        Err(e) => panic!("fixture must build, got {e:?}"),
    }
}

fn status_name(s: i8) -> &'static str {
    match s {
        UNBOUNDED => "UNBOUNDED",
        INACTIVE => "INACTIVE",
        WEAKLY_ACTIVE => "WEAKLY_ACTIVE",
        STRONGLY_ACTIVE => "STRONGLY_ACTIVE",
        AMBIGUOUS => "AMBIGUOUS",
        UNIDENTIFIED => "UNIDENTIFIED",
        _ => "other",
    }
}

// ---------------------------------------------------------------------------
// The basic verdicts.
// ---------------------------------------------------------------------------

/// A bound that holds its coordinate classifies strongly active; one that does
/// nothing classifies inactive; one with no finite bound is not classified.
#[test]
fn a_held_bound_a_slack_bound_and_a_free_variable_are_told_apart() {
    // `min ½‖x‖² − 4x₀ + x₁ + x₂  s.t.  x₀ + x₁ + x₂ = 1`,
    // x₀ ∈ [0, 0.5] (upper bound binds hard), x₁ ≥ 0 (binds), x₂ free.
    let prob = QpProblem {
        n: 3,
        p_lower: vec![tri(0, 0, 1.0), tri(1, 1, 1.0), tri(2, 2, 1.0)],
        c: vec![-4.0, 1.0, 0.0],
        a: vec![tri(0, 0, 1.0), tri(0, 1, 1.0), tri(0, 2, 1.0)],
        b: vec![1.0],
        g: vec![],
        h: vec![],
        lb: vec![0.0, 0.0, f64::NEG_INFINITY],
        ub: vec![0.5, f64::INFINITY, f64::INFINITY],
    };
    let rep = solved(&prob).activity();

    assert_eq!(
        rep.var_status[0],
        STRONGLY_ACTIVE,
        "x0 is pinned at its upper bound, got {}",
        status_name(rep.var_status[0])
    );
    assert_eq!(
        rep.var_status[2],
        UNBOUNDED,
        "x2 has no finite bound, got {}",
        status_name(rep.var_status[2])
    );
    assert!(
        rep.mu > 0.0 && rep.mu < 1e-6,
        "the report carries the achieved complementarity, got {}",
        rep.mu
    );
}

/// A variable's `Σ` sums both sides, so an *upper* bound is classified from its
/// own slack and multiplier rather than from the lower one's.
#[test]
fn an_upper_bound_is_classified_from_its_own_side() {
    // x₀ ∈ [0, 0.5] with the objective pushing it up: the UPPER bound is what
    // holds it, and the lower one is slack.
    let prob = QpProblem {
        n: 2,
        p_lower: vec![tri(0, 0, 1.0), tri(1, 1, 1.0)],
        c: vec![-4.0, 0.0],
        a: vec![tri(0, 0, 1.0), tri(0, 1, 1.0)],
        b: vec![1.0],
        g: vec![],
        h: vec![],
        lb: vec![0.0, f64::NEG_INFINITY],
        ub: vec![0.5, f64::INFINITY],
    };
    let rep = solved(&prob).activity();
    assert_eq!(
        rep.var_status[0],
        STRONGLY_ACTIVE,
        "the upper bound holds x0; dropping the `z_ub/s_ub` term from Σ would \
         report it inactive. Got {} with Σ = {}",
        status_name(rep.var_status[0]),
        rep.var_sigma[0]
    );
}

/// A coordinate with no curvature has no bound question to answer: the
/// classifier says so rather than guessing.
#[test]
fn a_flat_direction_is_unidentified_not_inactive() {
    // `min −x₀ s.t. x₀ + x₁ = 1, 0 ≤ x₀ ≤ 1`, with NO quadratic term on x₀.
    let prob = QpProblem {
        n: 2,
        p_lower: vec![tri(1, 1, 1.0)],
        c: vec![-1.0, 0.0],
        a: vec![tri(0, 0, 1.0), tri(0, 1, 1.0)],
        b: vec![1.0],
        g: vec![],
        h: vec![],
        lb: vec![0.0, f64::NEG_INFINITY],
        ub: vec![1.0, f64::INFINITY],
    };
    let rep = solved(&prob).activity();
    assert_eq!(
        rep.var_status[0],
        UNIDENTIFIED,
        "x0 carries no curvature, so the ratio Σ/q is not a question the \
         classifier can answer; got {}",
        status_name(rep.var_status[0])
    );
}

// ---------------------------------------------------------------------------
// The row curvature's normalization.
// ---------------------------------------------------------------------------

/// A row's classification must not change when the row is multiplied through by
/// a constant. That is what the `‖∇g‖⁴` normalization buys, and without it the
/// verdict moves with an arbitrary modelling choice.
#[test]
fn a_row_classification_is_unmoved_by_rescaling_the_row() {
    let make = |scale: f64| QpProblem {
        n: 2,
        p_lower: vec![tri(0, 0, 1.0), tri(1, 1, 1.0)],
        c: vec![-1.0, -1.0],
        a: vec![],
        b: vec![],
        g: vec![tri(0, 0, scale), tri(0, 1, scale)],
        h: vec![0.5 * scale],
        lb: vec![f64::NEG_INFINITY; 2],
        ub: vec![f64::INFINITY; 2],
    };
    let plain = solved(&make(1.0)).activity();
    let scaled = solved(&make(1000.0)).activity();

    assert_eq!(
        plain.row_status[0],
        scaled.row_status[0],
        "scaling a row by 1000 must not change what it is doing: {} vs {} \
         (ratios {} vs {})",
        status_name(plain.row_status[0]),
        status_name(scaled.row_status[0]),
        plain.row_ratio[0],
        scaled.row_ratio[0]
    );
    // The *band* is the claim, and the raw ratio deliberately is not.
    //
    // Measured: 1.2e9 against 1.4e11 for the two scalings above. The formula is
    // exactly invariant — `Σ·‖∇g‖²` and `∇gᵀP∇g/‖∇g‖²` each cancel the `c`
    // powers — but at a *hard-active* row `Σ = z/s` is dominated by how close to
    // zero the solve drove `s`, and that is set by the absolute tolerance, which
    // rescaling moves. So the ratio's magnitude there reports solver noise, and
    // asserting on it would be asserting on the stopping rule.
    //
    // Both extremes have this property: at an inactive row it is `z` rather
    // than `s` that is noise. Only a weakly-active row carries an `O(1)` ratio
    // that means something, which is why the invariance claim in this file is
    // about which class the row lands in.
    assert!(
        plain.row_ratio[0] > 1e1 && scaled.row_ratio[0] > 1e1,
        "both must still be far above the band — the shared verdict is not an \
         accident of both landing in the same wrong place: {} and {}",
        plain.row_ratio[0],
        scaled.row_ratio[0]
    );
}

// ---------------------------------------------------------------------------
// The rule this file exists for.
// ---------------------------------------------------------------------------

/// **A genuine kink on a coupled coordinate reads `AMBIGUOUS`.**
///
/// Two fixtures, same kink, differing only in whether the kinked coordinate is
/// coupled to another through the Hessian. Decoupled, the ratio is
/// `reduced/diagonal = 1` and the kink is certified `WEAKLY_ACTIVE`. Coupled,
/// the reduced curvature is smaller than the diagonal, the ratio moves off 1,
/// and the same kink lands in `AMBIGUOUS`.
///
/// The second verdict is not a bug — it is the classifier answering the cheap
/// question honestly. The bug would be a caller concluding "ambiguous, so no
/// kink", which is precisely what gh#763 was. Asserting that the two fixtures
/// **land in different classes** is what makes this evidence rather than
/// decoration: it shows the class tracks coupling, not kink-ness.
#[test]
fn an_ambiguous_verdict_does_not_mean_no_kink() {
    // A kink: the bound on x₀ is active with a multiplier vanishing alongside
    // its slack. `coupling` puts an off-diagonal P entry between x₀ and x₁.
    let make = |coupling: f64| {
        let mut p = vec![tri(0, 0, 1.0), tri(1, 1, 1.0)];
        if coupling != 0.0 {
            p.push(tri(1, 0, coupling)); // lower triangle
        }
        QpProblem {
            n: 2,
            p_lower: p,
            c: vec![0.0, 0.0],
            a: vec![tri(0, 0, 1.0), tri(0, 1, 1.0)],
            b: vec![1.0],
            g: vec![],
            h: vec![],
            // x₀'s lower bound sits exactly where the unconstrained optimum
            // puts it, so slack and multiplier vanish together.
            lb: vec![0.5, f64::NEG_INFINITY],
            ub: vec![f64::INFINITY; 2],
        }
    };

    let decoupled = solved(&make(0.0)).activity();
    let coupled = solved(&make(0.97)).activity();

    let a = decoupled.var_status[0];
    let b = coupled.var_status[0];

    // The precondition that makes the rest meaningful: the two fixtures take
    // DIFFERENT branches. Without this the test says nothing about coupling.
    assert_ne!(
        a,
        b,
        "the decoupled and coupled kinks must land in different classes, or \
         this fixture pair is not exercising the rule at all: both {} \
         (ratios {} and {})",
        status_name(a),
        decoupled.var_ratio[0],
        coupled.var_ratio[0]
    );
    assert_eq!(
        a,
        WEAKLY_ACTIVE,
        "a DECOUPLED kink has ratio ≈ 1 and is certified weakly active; got {} \
         with ratio {}",
        status_name(a),
        decoupled.var_ratio[0]
    );
    assert_eq!(
        b,
        AMBIGUOUS,
        "the SAME kink, coupled, reads ambiguous — because the ratio is \
         reduced/diagonal, not because the kink went away. Reading this as \
         'no kink' is the gh#763 error. Got {} with ratio {}",
        status_name(b),
        coupled.var_ratio[0]
    );
}

/// The ambiguity above is **μ-independent**: it is a property of the coupling,
/// not of how tightly the problem was solved. Someone who assumes a tighter
/// solve will resolve it needs this stated as a measurement.
#[test]
fn the_coupled_ambiguity_does_not_resolve_with_a_tighter_solve() {
    let prob = QpProblem {
        n: 2,
        p_lower: vec![tri(0, 0, 1.0), tri(1, 1, 1.0), tri(1, 0, 0.97)],
        c: vec![0.0, 0.0],
        a: vec![tri(0, 0, 1.0), tri(0, 1, 1.0)],
        b: vec![1.0],
        g: vec![],
        h: vec![],
        lb: vec![0.5, f64::NEG_INFINITY],
        ub: vec![f64::INFINITY; 2],
    };
    for tol in [1e-8, 1e-10, 1e-12] {
        let opts = QpOptions {
            tol,
            ..Default::default()
        };
        let sol = solve_qp_ipm(&prob, &opts, backend);
        assert_eq!(sol.status, QpStatus::Optimal);
        let Ok(sens) = QpSensitivity::build(&prob, &sol, &opts, 1e-7, backend) else {
            panic!("must build at tol {tol}");
        };
        let rep = sens.activity();
        assert_eq!(
            rep.var_status[0], AMBIGUOUS,
            "at tol {tol} the coupled kink still reads ambiguous (ratio {}, \
             mu {}) — the ratio is reduced/diagonal, which does not move with μ",
            rep.var_ratio[0], rep.mu
        );
    }
}

// ---------------------------------------------------------------------------
// What `mu` is, stated so a cross-arm comparison is not written against it.
// ---------------------------------------------------------------------------

/// The report's `μ` is the achieved complementarity, which is what makes it
/// derivable without a barrier iterate — and what makes it the wrong thing to
/// demand bit-agreement on with the NLP arm.
#[test]
fn the_mu_is_the_achieved_complementarity() {
    let prob = QpProblem {
        n: 2,
        p_lower: vec![tri(0, 0, 1.0), tri(1, 1, 1.0)],
        c: vec![-4.0, 0.0],
        a: vec![tri(0, 0, 1.0), tri(0, 1, 1.0)],
        b: vec![1.0],
        g: vec![],
        h: vec![],
        lb: vec![0.0, f64::NEG_INFINITY],
        ub: vec![0.5, f64::INFINITY],
    };
    let sens = solved(&prob);
    let rep = sens.activity();
    assert_eq!(
        rep.mu,
        sens.duality_measure(),
        "the report bands against exactly `duality_measure()`; if these ever \
         diverge, a caller reading one and reasoning about the other is wrong"
    );
}
